language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - xbuild CI.proj
  - nunit-console ./src/Aluno.Testes/bin/Debug/Aluno.Testes.dll -exclude Integration,NotWorkingOnMono
