//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Aluno.Entity
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class AlunoEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto AlunoEntities usando a cadeia de conexão localizada na seção 'AlunoEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public AlunoEntities() : base("name=AlunoEntities", "AlunoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto AlunoEntities.
        /// </summary>
        public AlunoEntities(string connectionString) : base(connectionString, "AlunoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto AlunoEntities.
        /// </summary>
        public AlunoEntities(EntityConnection connection) : base(connection, "AlunoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<aluno> Aluno
        {
            get
            {
                if ((_Aluno == null))
                {
                    _Aluno = base.CreateObjectSet<aluno>("Aluno");
                }
                return _Aluno;
            }
        }
        private ObjectSet<aluno> _Aluno;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<Professor> Professor
        {
            get
            {
                if ((_Professor == null))
                {
                    _Professor = base.CreateObjectSet<Professor>("Professor");
                }
                return _Professor;
            }
        }
        private ObjectSet<Professor> _Professor;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet Aluno. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToAluno(aluno aluno)
        {
            base.AddObject("Aluno", aluno);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet Professor. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToProfessor(Professor professor)
        {
            base.AddObject("Professor", professor);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlunoModel", Name="aluno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aluno : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto aluno.
        /// </summary>
        /// <param name="idAluno">Valor inicial da propriedade IdAluno.</param>
        /// <param name="nome">Valor inicial da propriedade Nome.</param>
        /// <param name="cPF">Valor inicial da propriedade CPF.</param>
        /// <param name="matricula">Valor inicial da propriedade Matricula.</param>
        public static aluno Createaluno(global::System.Int32 idAluno, global::System.String nome, global::System.String cPF, global::System.String matricula)
        {
            aluno aluno = new aluno();
            aluno.IdAluno = idAluno;
            aluno.Nome = nome;
            aluno.CPF = cPF;
            aluno.Matricula = matricula;
            return aluno;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAluno
        {
            get
            {
                return _IdAluno;
            }
            set
            {
                if (_IdAluno != value)
                {
                    OnIdAlunoChanging(value);
                    ReportPropertyChanging("IdAluno");
                    _IdAluno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdAluno");
                    OnIdAlunoChanged();
                }
            }
        }
        private global::System.Int32 _IdAluno;
        partial void OnIdAlunoChanging(global::System.Int32 value);
        partial void OnIdAlunoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Matricula
        {
            get
            {
                return _Matricula;
            }
            set
            {
                OnMatriculaChanging(value);
                ReportPropertyChanging("Matricula");
                _Matricula = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Matricula");
                OnMatriculaChanged();
            }
        }
        private global::System.String _Matricula;
        partial void OnMatriculaChanging(global::System.String value);
        partial void OnMatriculaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlunoModel", Name="Professor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Professor : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto Professor.
        /// </summary>
        /// <param name="idProfessor">Valor inicial da propriedade idProfessor.</param>
        /// <param name="nome">Valor inicial da propriedade Nome.</param>
        /// <param name="especializacao">Valor inicial da propriedade Especializacao.</param>
        /// <param name="materia">Valor inicial da propriedade Materia.</param>
        public static Professor CreateProfessor(global::System.Int32 idProfessor, global::System.String nome, global::System.String especializacao, global::System.String materia)
        {
            Professor professor = new Professor();
            professor.idProfessor = idProfessor;
            professor.Nome = nome;
            professor.Especializacao = especializacao;
            professor.Materia = materia;
            return professor;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProfessor
        {
            get
            {
                return _idProfessor;
            }
            set
            {
                if (_idProfessor != value)
                {
                    OnidProfessorChanging(value);
                    ReportPropertyChanging("idProfessor");
                    _idProfessor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idProfessor");
                    OnidProfessorChanged();
                }
            }
        }
        private global::System.Int32 _idProfessor;
        partial void OnidProfessorChanging(global::System.Int32 value);
        partial void OnidProfessorChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Especializacao
        {
            get
            {
                return _Especializacao;
            }
            set
            {
                OnEspecializacaoChanging(value);
                ReportPropertyChanging("Especializacao");
                _Especializacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Especializacao");
                OnEspecializacaoChanged();
            }
        }
        private global::System.String _Especializacao;
        partial void OnEspecializacaoChanging(global::System.String value);
        partial void OnEspecializacaoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Materia
        {
            get
            {
                return _Materia;
            }
            set
            {
                OnMateriaChanging(value);
                ReportPropertyChanging("Materia");
                _Materia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Materia");
                OnMateriaChanged();
            }
        }
        private global::System.String _Materia;
        partial void OnMateriaChanging(global::System.String value);
        partial void OnMateriaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Graduacao
        {
            get
            {
                return _Graduacao;
            }
            set
            {
                OnGraduacaoChanging(value);
                ReportPropertyChanging("Graduacao");
                _Graduacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Graduacao");
                OnGraduacaoChanged();
            }
        }
        private global::System.String _Graduacao;
        partial void OnGraduacaoChanging(global::System.String value);
        partial void OnGraduacaoChanged();

        #endregion

    
    }

    #endregion

    
}
